//
//  AreaCodes.m
//  AreaCode
//
//  Created by Cameron Briar on 1/15/11.
//  Copyright 2011 CSU Fresno. All rights reserved.
//

#import "AreaCodes.h"


@implementation AreaCodes
@synthesize areaCodes;
@synthesize county;

-(id) init {
	if ([super init] == nil) {
		return nil;
	}
	areaCodes = [[NSArray alloc] initWithObjects:@"201",
				 @"202",
				 @"203",
				 @"204",
				 @"205",
				 @"206",
				 @"207",
				 @"208",
				 @"209",
				 @"210",
				 @"212",
				 @"213",
				 @"214",
				 @"215",
				 @"216",
				 @"217",
				 @"218",
				 @"219",
				 @"224",
				 @"225",
				 @"226",
				 @"228",
				 @"229",
				 @"231",
				 @"234",
				 @"236",
				 @"239",
				 @"240",
				 @"242",
				 @"246",
				 @"248",
				 @"250",
				 @"251",
				 @"252",
				 @"253",
				 @"254",
				 @"256",
				 @"260",
				 @"262",
				 @"264",
				 @"267",
				 @"268",
				 @"269",
				 @"270",
				 @"276",
				 @"278",
				 @"280",
				 @"281",
				 @"282",
				 @"283",
				 @"284",
				 @"289",
				 @"301",
				 @"302",
				 @"303",
				 @"304",
				 @"305",
				 @"306",
				 @"307",
				 @"308",
				 @"309",
				 @"310",
				 @"311",
				 @"312",
				 @"313",
				 @"314",
				 @"315",
				 @"316",
				 @"317",
				 @"318",
				 @"319",
				 @"320",
				 @"321",
				 @"323",
				 @"325",
				 @"330",
				 @"331",
				 @"334",
				 @"336",
				 @"337",
				 @"339",
				 @"340",
				 @"345",
				 @"347",
				 @"351",
				 @"352",
				 @"353",
				 @"354",
				 @"356",
				 @"358",
				 @"360",
				 @"361",
				 @"369",
				 @"380",
				 @"383",
				 @"384",
				 @"385",
				 @"386",
				 @"401",
				 @"402",
				 @"403",
				 @"404",
				 @"405",
				 @"406",
				 @"407",
				 @"408",
				 @"409",
				 @"410",
				 @"411",
				 @"412",
				 @"413",
				 @"414",
				 @"415",
				 @"416",
				 @"417",
				 @"418",
				 @"419",
				 @"423",
				 @"424",
				 @"425",
				 @"430",
				 @"432",
				 @"434",
				 @"435",
				 @"438",
				 @"440",
				 @"441",
				 @"443",
				 @"450",
				 @"456",
				 @"464",
				 @"469",
				 @"470",
				 @"473",
				 @"475",
				 @"478",
				 @"479",
				 @"480",
				 @"484",
				 @"500",
				 @"501",
				 @"502",
				 @"503",
				 @"504",
				 @"505",
				 @"506",
				 @"507",
				 @"508",
				 @"509",
				 @"510",
				 @"511",
				 @"512",
				 @"513",
				 @"514",
				 @"515",
				 @"516",
				 @"517",
				 @"518",
				 @"519",
				 @"520",
				 @"530",
				 @"540",
				 @"541",
				 @"546",
				 @"551",
				 @"557",
				 @"559",
				 @"561",
				 @"562",
				 @"563",
				 @"564",
				 @"567",
				 @"570",
				 @"571",
				 @"573",
				 @"574",
				 @"580",
				 @"585",
				 @"586",
				 @"590",
				 @"600",
				 @"601",
				 @"602",
				 @"603",
				 @"604",
				 @"605",
				 @"606",
				 @"607",
				 @"608",
				 @"609",
				 @"610",
				 @"612",
				 @"613",
				 @"614",
				 @"615",
				 @"616",
				 @"617",
				 @"618",
				 @"619",
				 @"620",
				 @"623",
				 @"626",
				 @"630",
				 @"631",
				 @"636",
				 @"641",
				 @"646",
				 @"647",
				 @"650",
				 @"651",
				 @"657",
				 @"660",
				 @"661",
				 @"662",
				 @"664",
				 @"669",
				 @"671",
				 @"678",
				 @"682",
				 @"689",
				 @"700",
				 @"701",
				 @"702",
				 @"703",
				 @"704",
				 @"705",
				 @"706",
				 @"707",
				 @"708",
				 @"709",
				 @"710",
				 @"712",
				 @"713",
				 @"714",
				 @"715",
				 @"716",
				 @"717",
				 @"718",
				 @"719",
				 @"720",
				 @"724",
				 @"727",
				 @"731",
				 @"732",
				 @"734",
				 @"737",
				 @"740",
				 @"757",
				 @"758",
				 @"760",
				 @"763",
				 @"765",
				 @"770",
				 @"772",
				 @"773",
				 @"774",
				 @"775",
				 @"778",
				 @"780",
				 @"781",
				 @"784",
				 @"785",
				 @"786",
				 @"787",
				 @"800",
				 @"801",
				 @"802",
				 @"803",
				 @"804",
				 @"805",
				 @"806",
				 @"807",
				 @"808",
				 @"809",
				 @"810",
				 @"812",
				 @"813",
				 @"814",
				 @"815",
				 @"816",
				 @"817",
				 @"818",
				 @"819",
				 @"822",
				 @"828",
				 @"830",
				 @"831",
				 @"832",
				 @"833",
				 @"835",
				 @"843",
				 @"844",
				 @"845",
				 @"847",
				 @"848",
				 @"850",
				 @"855",
				 @"856",
				 @"857",
				 @"858",
				 @"859",
				 @"860",
				 @"861",
				 @"862",
				 @"863",
				 @"864",
				 @"865",
				 @"866",
				 @"867",
				 @"868",
				 @"869",
				 @"870",
				 @"872",
				 @"876",
				 @"877",
				 @"878",
				 @"888",
				 @"898",
				 @"900",
				 @"901",
				 @"902",
				 @"903",
				 @"904",
				 @"905",
				 @"906",
				 @"907",
				 @"908",
				 @"909",
				 @"910",
				 @"911",
				 @"912",
				 @"913",
				 @"914",
				 @"915",
				 @"916",
				 @"917",
				 @"918",
				 @"919",
				 @"920",
				 @"925",
				 @"928",
				 @"931",
				 @"935",
				 @"936",
				 @"937",
				 @"939",
				 @"940",
				 @"941",
				 @"947",
				 @"949",
				 @"951",
				 @"952",
				 @"954",
				 @"956",
				 @"959",
				 @"970",
				 @"971",
				 @"972",
				 @"973",
				 @"975",
				 @"976",
				 @"978",
				 @"979",
				 @"980",
				 @"984",
				 @"985",
				 @"989",nil];
	county = [[NSArray alloc] initWithObjects:@"N New Jersey: Jersey City, Hackensack",
			  @"Washington, D.C.",
			  @"Connecticut",
			  @"Manitoba Canada",
			  @"Central and Western Alabama",
			  @"W. Washington state: Seattle",
			  @"Maine",
			  @"Idaho",
			  @"Central California",
			  @"San Antonio S. Texas",
			  @"New York City, New York",
			  @"Los Angeles California",
			  @"Dallas Texas",
			  @"Philadelphia Pennsylvania",
			  @"Cleveland",
			  @"Central Illinois",
			  @"North Minnesota",
			  @"North Indiana",
			  @"Northern NE Illinois",
			  @"Louisiana: Baton Rouge",
			  @"SW Ontario Canada",
			  @"South Mississippi",
			  @"SW Georgia",
			  @"Michigan",
			  @"NE Ohio",
			  @"Virginia",
			  @"Florida",
			  @"West Maryland: Silver Spring, Frederick",
			  @"Bahamas",
			  @"Barbados",
			  @"Michigan: Oakland county",
			  @"British Columbia",
			  @"South Alabama",
			  @"NE Carolina",
			  @"South Washington",
			  @"Central Texas",
			  @"Huntsville, Alabama",
			  @"NE Indiana",
			  @"Wisconsin, surrounding Milwaukee",
			  @"Anguilla",
			  @"SE Pennsylvania: Philadelphia",
			  @"Antigua and Barbuda",
			  @"SW Michigan",
			  @"West Kentucky",
			  @"South Virginia",
			  @"Michigan",
			  @"Maryland",
			  @"Texas: Houston Metro",
			  @"Illinois",
			  @"SW Ohio",
			  @"British Virgin Islands",
			  @"South Central Canada",
			  @"W Maryland: Silver Spring, Frederick",
			  @"Delaware",
			  @"Central Colorado: Denver",
			  @"West Virginia",
			  @"SE Florida: Miami",
			  @"Saskatchewan Canada",
			  @"Wyoming",
			  @"West Nebraska",
			  @"West Central Illinois",
			  @"South California: Los Angeles",
			  @"Reserved / Municipal Assistance",
			  @"Chicago, Illinois (Downtown only)",
			  @"Detroit and suburbs",
			  @"SE Missouri: St Louis metro area only",
			  @"North Central New York",
			  @"South Kansas",
			  @"Central Indiana",
			  @"Northern Louisiana",
			  @"East Iowa",
			  @"Central. Minnesota",
			  @"Florida",
			  @"Los Angeles",
			  @"Central Texas",
			  @"NE Ohio: Akron, Canton, and Youngstown area",
			  @"NE Illinois",
			  @"South Alabama",
			  @"Central North Carolina",
			  @"SW Louisiana",
			  @"Boston Massachusetts",
			  @"US Virgin Islands",
			  @"Cayman Islands",
			  @"New York",
			  @"North Massachusetts",
			  @"Florida",
			  @"Wisconsin",
			  @"Florida",
			  @"New Jersey",
			  @"Pennsylvania",
			  @"W. Washington State",
			  @"Corpus Christi",
			  @"California",
			  @"Ohio",
			  @"Maine",
			  @"Ohio",
			  @"Utah",
			  @"Daytona Beach, Florida",
			  @"Rhode Island",
			  @"East Nebraska",
			  @"Alberta",
			  @"N Georgia: Atlanta",
			  @"Oklahoma City metro",
			  @"Montana",
			  @"Central Florida: Metro Orlando",
			  @"Cupertino, Santa Clara, and San Jose area",
			  @"SE Texas: Galveston, Port Arthur",
			  @"East Maryland",
			  @"Not an area code - information",
			  @"West Pennsylvania",
			  @"West Massachusetts",
			  @"SE Wisconsin: Milwaukee",
			  @"San Francisco, California",
			  @"Canada: Metrolpolitan Toronto",
			  @"SW Missouri: Springfield",
			  @"NE Quebec",
			  @"NW Ohio: Toledo",
			  @"East Tennessee",
			  @"Los Angeles, South California",
			  @"North Washington",
			  @"NE Texas",
			  @"West Texas",
			  @"East Virginia",
			  @"Utah outside Salt Lake City",
			  @"Canada: SW Quebec",
			  @"Ohio: Cleveland metro area, excluding Cleveland",
			  @"Bermuda",
			  @"East Maryland",
			  @"Southeastern Quebec outside metro Montreal",
			  @"International Inbound",
			  @"Illinois",
			  @"Texas",
			  @"Georgia",
			  @"Grenada",
			  @"Connecticut",
			  @"Central Georgia",
			  @"NW Arkansas",
			  @"Arizona",
			  @"SE Pennsylvania: Allentown, Reading",
			  @"Personal Services",
			  @"Central Arkansas",
			  @"W Kentucky: Louisville",
			  @"Oregon",
			  @"East Louisiana: New Orleans",
			  @"New Mexico",
			  @"New Brunswick Canada",
			  @"South Minnesota: Rochester",
			  @"Cent. Massachusetts: Framingham",
			  @"East Washington",
			  @"California: Oakland, East Bay",
			  @"Travel information line.",
			  @"Austin",
			  @"SW Ohio",
			  @"SW Quebec: Montreal",
			  @"Central Iowa",
			  @"Nassau county on Long Island and New York: Hempstead",
			  @"Central Michigan",
			  @"NE New York: Albany",
			  @"SW Ontario: Windsor",
			  @"Arizona outside the Phoenix area",
			  @"NE California: Chico, Redding",
			  @"Fredericksburg and Roanoke and nearby areas",
			  @"Oregon",
			  @"E Michigan",
			  @"North New Jersey",
			  @"SE Missouri",
			  @"California: Fresno",
			  @"Florida (S. Central) (West Palm Beach, Boca Raton, Vero Beach)",
			  @"California: Long Beach",
			  @"East Iowa",
			  @"West Washington",
			  @"NW Ohio",
			  @"E Pennsylvania: Wilkes-Barre, Scranton",
			  @"North Virginia",
			  @"SE Missouri: excluding St Louis metro area",
			  @"North Indiana",
			  @"Western and Southern Oklahoma",
			  @"NW New York: Rochester",
			  @"Michigan",
			  @"French West Indies",
			  @"Canadian Services",
			  @"Mississippi",
			  @"Phoenix Arizona",
			  @"New Hampshire",
			  @"Canada: British Columbia, Greater Vancouver",
			  @"South Dakota",
			  @"East Kentucky: Ashland",
			  @"South Central New York: Ithaca, Binghamton",
			  @"SW Wisconsin: Madison",
			  @"South New Jersey: Trenton",
			  @"SE Pennsylvania: Allentown, Reading",
			  @"Central Minnesota, Minneapolis",
			  @"Canada: SE Ontario, Ottawa",
			  @"SE Ohio: Columbus",
			  @"East Tennessee: Nashville",
			  @"West Michigan: Grand Rapids",
			  @"East Massachusetts: Boston",
			  @"South Illinois",
			  @"South California: San Diego",
			  @"South Kansas: Wichita",
			  @"Arizona",
			  @"SE California: Pasadena",
			  @"NE Illinois, Oak Brook or Chicago suburbs",
			  @"New York: Suffolk County",
			  @"Missouri",
			  @"Iowa",
			  @"Manhattan New York",
			  @"South Central Ontario",
			  @"Peninsula south of San Francisco",
			  @"Central Minnesota, St. Paul",
			  @"Orange County, California",
			  @"North Missouri",
			  @"California: N. Los Angeles, Mojave",
			  @"Mississippi",
			  @"Montserrat",
			  @"Central California coast",
			  @"Guam",
			  @"North Georgia: Atlanta",
			  @"Fort Worth Texas",
			  @"Central Florida",
			  @"Interconnect Services",
			  @"North Dakota",
			  @"South Nevada",
			  @"Northern Virginia: Arlington, McLean, Tysons Corner",
			  @"West North Carolina: Charlotte",
			  @"Canada: NW Ontario, Sault Ste. Marie",
			  @"North Georgia: Columbus, Augusta",
			  @"NW California: Santa Rosa",
			  @"Central NE Illinois: Oak Brook",
			  @"Canada Newfoundland",
			  @"US Government",
			  @"West Iowa",
			  @"Mid SE Texas: Houston",
			  @"North Orange County, California",
			  @"North Wisconsin: Eau Claire",
			  @"NW New York: Buffalo, Rochester",
			  @"East Pennsylvania: Wilkes-Barre, Scranton",
			  @"New York City, New York",
			  @"SE Colorado: Pueblo, Colorado Springs",
			  @"Central Colorado: Denver",
			  @"SW Pennsylvania",
			  @"Tampa Metro: Saint Petersburg, Clearwater",
			  @"West Tennessee",
			  @"Central New Jersey: New Brunswick, Bound Brook",
			  @"SE Michigan: west and south of Detroit -- Ann Arbor, Monroe",
			  @"South Texas",
			  @"SE Ohio",
			  @"E Virginia, Williamsburgh area, including Portsmouth",
			  @"St. Lucia",
			  @"California: Southeastern San Diego north to Sierra Nevada",
			  @"Minnesota",
			  @"Indiana: outside Indianapolis",
			  @"Atlanta and suburbs",
			  @"South central Florida",
			  @"Non-downtown Chicago, Illinois",
			  @"Massachusetts",
			  @"Nevada",
			  @"British Colombia Canada",
			  @"Alberta Canada",
			  @"E Massachusetts: Boston suburbs",
			  @"St. Vincent/Grenadines",
			  @"N Kansas: Topeka",
			  @"SE Florida",
			  @"Puerto Rico",
			  @"Domestic Toll-Free",
			  @"Salt Lake City Metro",
			  @"Vermont",
			  @"South Carolina",
			  @"East Virginia: Richmond",
			  @"South Central Coastal California: Bakersfield",
			  @"Panhandle Texas: Amarillo",
			  @"Canada: West Ontario, Thunder Bay",
			  @"HAWAII",
			  @"Bermuda, Puerto Rico, Virgin Islands, Caribbean",
			  @"East Michigan: Flint, Pontiac",
			  @"South Indiana: Evansville",
			  @"SW Florida: Tampa Metro",
			  @"Central Pennsylvania: Erie",
			  @"NE Illinois: Rockford, Kankakee",
			  @"N Missouri: Kansas City",
			  @"N Cent. Texas: Fort Worth area",
			  @"S California: Los Angeles",
			  @"Canada: NW Quebec: Trois Rivieres",
			  @"US/Canada Toll-Free",
			  @"West North Carolina: Asheville",
			  @"Texas: North and West of San Antonio",
			  @"California: central coast area from Santa Cruz through Monterey County",
			  @"Texas",
			  @"US/Canada Toll-Free",
			  @"SE Pennsylvania",
			  @"South Carolina",
			  @"US/Canada Toll-Free",
			  @"New York",
			  @"Northern NE Illinois: Oak Brook",
			  @"Central New Jersey",
			  @"Florida panhandle, from east of Tallahassee to Pensacola",
			  @"US/Canada Toll-Free",
			  @"SW New Jersey",
			  @"Massachusetts",
			  @"S California: San Diego",
			  @"Kentucky",
			  @"Connecticut",
			  @"SW Florida",
			  @"North New Jersey",
			  @"Florida",
			  @"South Carolina",
			  @"Tennessee",
			  @"US/Canada Toll-Free",
			  @"Canada: Yukon and Northwest Territories",
			  @"Trindad & Tobago",
			  @"St. Kitts/Nevis",
			  @"South Arkansas",
			  @"Illinois: Chicago",
			  @"Jamaica",
			  @"Domestic Toll-Free",
			  @"Pittsburgh",
			  @"Domestic Toll-Free",
			  @"VoIP service",
			  @"Personal paid service line",
			  @"W Tennessee: Memphis",
			  @"Canada: Nova Scotia, Prince Edward Island",
			  @"NE Texas: Tyler",
			  @"North Florida: Jacksonville",
			  @"South central Ontario",
			  @"Upper Peninsula Michigan: Sault Ste. Marie, Escanaba, Marquette",
			  @"Alaska",
			  @"Cent. New Jersey: Elizabeth, Basking Ridge, Somerville, Bridgewater",
			  @"Inland empire: San Bernandino",
			  @"South Central North Carolina: Fayetteville, Wilmington",
			  @"Emergency Help",
			  @"South Georgia: Savannah",
			  @"North East Kansas/Kansas City Metro/Leavenworth",
			  @"South New York: White Plains",
			  @"West Texas: Sweetwater",
			  @"NE California: Sacramento",
			  @"New York City, New York",
			  @"East Oklahoma: Tulsa",
			  @"East North Carolina: Raleigh",
			  @"NE Wisconsin",
			  @"California",
			  @"Arizona",
			  @"Central Tennessee",
			  @"South California: San Diego",
			  @"SE Texas",
			  @"SW Ohio: Dayton",
			  @"Puerto Rico",
			  @"North Central Texas: Denton, Wichita Falls",
			  @"SW Florida: Tampa Area",
			  @"Michigan",
			  @"South Coastal Orange County California",
			  @"West riverside California",
			  @"Minnesota",
			  @"Broward County area, including Ft. Lauderdale",
			  @"Valley of Texas area (Harlingen)",
			  @"Connecticut",
			  @"North and West Colorado",
			  @"Oregon",
			  @"Texas: Dallas Metro: Dallas and parts of Denton and Collin counties",
			  @"North New Jersey: Newark Paterson Morristown",
			  @"North Missouri",
			  @"Personal paid service line",
			  @"Central Massachusetts",
			  @"SE Texas",
			  @"Carolina",
			  @"Carolina",
			  @"E Louisiana",
			  @"Michigan",
			  nil];
	return self;
}

@end
